package com.msoumaya.androidcoran.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.msoumaya.androidcoran.domain.*
import kotlinx.serialization.json.*
import java.time.LocalDate
import java.time.Instant

@Composable fun FriendsScreen(vm: CoranViewModel) {
    var profile by remember { mutableStateOf<JsonObject?>(null) };var links by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var profiles by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var groups by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var messages by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var room by rememberSaveable { mutableStateOf<String?>(null) };var groupRoom by rememberSaveable { mutableStateOf(false) };var body by rememberSaveable { mutableStateOf("") };var code by rememberSaveable { mutableStateOf("") };var groupName by rememberSaveable { mutableStateOf("") }
    fun refresh() { vm.action { profile=vm.repo.rpc("ensure_social_profile").let { if(it is JsonArray) it.firstOrNull()?.jsonObject else it.jsonObject };links=vm.repo.rows("friend_links");profiles=vm.repo.rows("friend_profiles");groups=vm.repo.rows("friend_groups") } }
    fun loadRoom() { val id=room?:return;vm.action { messages=vm.repo.rows("friend_messages",mapOf((if(groupRoom) "group_id" else "link_id") to id)).sortedBy { it.str("created_at") } } }
    LaunchedEffect(vm.repo.user.value) { if(vm.repo.user.value!=null) refresh() }
    if(vm.repo.user.value==null) { PageList { Text("Connecte-toi pour retrouver tes amis et conversations") };return }
    Column(Modifier.padding(16.dp)) {
        if(room!=null) { TextButton(onClick={room=null}) { Text("Retour aux amis") };Button(onClick={loadRoom()}) { Text("Actualiser les messages") };LazyColumn(Modifier.weight(1f)) { items(messages,key={it.str("id")}) { message -> Panel(if(message.str("sender_id")==vm.repo.user.value) "Moi" else "Ami",if(message["deleted_at"]!=JsonNull&&message["deleted_at"]!=null) "Message supprimé" else message.str("body")) { if(message.str("kind")=="recitation") Text("Récitation partagée : ${message.str("recitation_id")}");if(message.str("sender_id")==vm.repo.user.value) TextButton(onClick={vm.action { vm.repo.rpc("delete_friend_message",json("p_message" to message.str("id")));loadRoom() }}) { Text("Supprimer") } } } };OutlinedTextField(body,{body=it},label={Text("Message")},modifier=Modifier.fillMaxWidth());Button(onClick={vm.action { require(body.trim().length in 1..2000);vm.repo.insert("friend_messages",json("link_id" to if(groupRoom) null else room,"group_id" to if(groupRoom) room else null,"sender_id" to vm.repo.user.value,"kind" to "text","body" to body.trim()));body="";loadRoom() }}) { Text("Envoyer") }
        } else LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)) {
            item { Text("Code d’invitation : ${profile?.str("invite_code")?:"…"}");OutlinedTextField(code,{code=it},label={Text("Code de l’ami")});Button(onClick={vm.action { vm.repo.rpc("request_friend",json("p_code" to code.trim()));refresh() }}) { Text("Ajouter un ami") };TextButton(onClick={refresh()}) { Text("Actualiser") } }
            items(links,key={it.str("id")}) { link -> val other=if(link.str("requester_id")==vm.repo.user.value) link.str("recipient_id") else link.str("requester_id");val name=profiles.firstOrNull { it.str("id")==other }?.str("display_name")?:other;Panel(name,link.str("status"),if(link.str("status")=="accepted") ({room=link.str("id");groupRoom=false;loadRoom()}) else null) { if(link.str("status")=="pending"&&link.str("recipient_id")==vm.repo.user.value) Row { TextButton(onClick={vm.action { vm.repo.rpc("accept_friend",json("p_link" to link.str("id")));refresh() }}) { Text("Accepter") };TextButton(onClick={vm.action { vm.repo.rpc("decline_friend",json("p_link" to link.str("id")));refresh() }}) { Text("Refuser") } } } }
            item { Text("Groupes",style=MaterialTheme.typography.titleLarge);OutlinedTextField(groupName,{groupName=it},label={Text("Nom du groupe")});Button(onClick={vm.action { vm.repo.rpc("create_friend_group",json("p_name" to groupName));groupName="";refresh() }}) { Text("Créer un groupe") } }
            items(groups,key={it.str("id")}) { group -> Panel(group.str("name"),onClick={room=group.str("id");groupRoom=true;loadRoom()}) }
        }
    }
}
@Composable fun ContentsScreen(vm: CoranViewModel) { var contents by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var type by rememberSaveable { mutableStateOf("reminder") };var daily by rememberSaveable { mutableStateOf(true) }
    fun load() { vm.action { contents=if(daily) vm.repo.cachedRpc("daily_content_for_date",json("p_date" to LocalDate.now().toString())).jsonArray.map { it.jsonObject } else vm.repo.rows("daily_contents",mapOf("type" to type,"is_active" to "true")) } }
    LaunchedEffect(type,daily,vm.repo.user.value) { if(vm.repo.user.value!=null) load() }
    Column(Modifier.padding(16.dp)) { Row { FilterChip(selected=daily,onClick={daily=!daily},label={Text("Aujourd’hui")});FilterChip(selected=type=="reminder",onClick={type="reminder";daily=false},label={Text("Rappels")});FilterChip(selected=type=="invocation",onClick={type="invocation";daily=false},label={Text("Invocations")}) };LazyColumn(verticalArrangement=Arrangement.spacedBy(10.dp)) { items(contents,key={it.str("id")}) { c -> Panel(c.str("title"),c.str("french_text")) { if(c.str("arabic_text").isNotEmpty()) Text(c.str("arabic_text"),fontSize=24.sp);Text(c.str("phonetic_text"));Text(c.str("explanation"));Text("${c.str("source")} ${c.str("reference")}",fontSize=12.sp) } };if(contents.isEmpty()) item { Text("Connecte-toi puis actualise pour charger les contenus") };item { Button(onClick={load()}) { Text("Actualiser") } } } }
}
@Composable fun QuizScreen(vm: CoranViewModel) { var snapshot by remember { mutableStateOf<JsonObject?>(null) };var opponent by rememberSaveable { mutableStateOf("") };var active by remember { mutableStateOf<JsonObject?>(null) }
    fun load() { vm.action { snapshot=vm.repo.cachedRpc("quiz_snapshot",json("p_day" to LocalDate.now().toString())).jsonObject } }
    LaunchedEffect(vm.repo.user.value) { if(vm.repo.user.value!=null) load() }
    PageList { Button(onClick={load()}) { Text("Actualiser le quiz") };val daily=snapshot?.get("daily") as? JsonObject
        if(daily!=null) { Text("Question du jour",style=MaterialTheme.typography.titleLarge);Text(daily.str("question"));val answered=snapshot!!.arr("responses").any { it.jsonObject.str("day")==LocalDate.now().toString() };daily.arr("answers").forEach { raw -> val a=raw.jsonObject;Button(enabled=!answered,onClick={vm.action { vm.repo.rpc("quiz_answer_daily",json("p_question" to daily.str("id"),"p_answer" to a.str("id"),"p_day" to LocalDate.now().toString(),"p_answered_at" to Instant.now().toString()));load() }}) { Text(a.str("text")) } };if(answered) Text("Réponse enregistrée") }
        Text("Défis entre amis",style=MaterialTheme.typography.titleLarge);OutlinedTextField(opponent,{opponent=it},label={Text("Identifiant de l’ami")});Row { listOf(5,10).forEach { count -> TextButton(onClick={vm.action { vm.repo.rpc("quiz_create_challenge",json("p_opponent" to opponent.trim(),"p_count" to count,"p_set" to null));load() }}) { Text("$count questions") } } }
        snapshot?.arr("challenges")?.forEach { raw -> val c=raw.jsonObject;Panel("${c.str("creatorName")} / ${c.str("opponentName")}","${c.str("status")} · expire ${c.str("expiresAt")}",{active=c}) }
        active?.let { c -> Text("Défi en cours");c.arr("questions").forEach { raw -> val question=raw.jsonObject;val answered=c.arr("answers").any { it.jsonObject.str("userId")==vm.repo.user.value&&it.jsonObject.str("questionId")==question.str("id") };Text(question.str("question"));question.arr("answers").forEach { a -> TextButton(enabled=!answered&&c.str("status")=="pending"&&Instant.parse(c.str("expiresAt"))>Instant.now(),onClick={vm.action { vm.repo.rpc("quiz_answer_challenge",json("p_challenge" to c.str("id"),"p_question" to question.str("id"),"p_answer" to a.jsonObject.str("id")));active=null;load() }}) { Text(a.jsonObject.str("text")) } } } }
    }
}
@Composable fun RecitationsScreen(vm: CoranViewModel) { var rows by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var corrections by remember { mutableStateOf<List<JsonObject>>(emptyList()) };var selected by remember { mutableStateOf<JsonObject?>(null) };val context=androidx.compose.ui.platform.LocalContext.current
    fun load() { vm.action { rows=vm.repo.rows("recitations",mapOf("user_id" to (vm.repo.user.value?:error("Connexion nécessaire")))) } }
    LaunchedEffect(vm.repo.user.value) { if(vm.repo.user.value!=null) load() }
    PageList { RecorderPanel(vm);Button(onClick={vm.action { vm.repo.uploadRecordings();load() }}) { Text("Envoyer les enregistrements sauvegardés") };Text("${vm.repo.recordings().count { !it.flag("synced") }} enregistrement(s) en attente");Button(onClick={load()}) { Text("Actualiser les récitations") };rows.forEach { r -> Panel(vm.repo.quran.reference(VerseRange(r.num("start_verse_id"),r.num("end_verse_id"))),r.str("created_at"),{selected=r;vm.action { corrections=vm.repo.rows("recitation_corrections",mapOf("recitation_id" to r.str("id"))) }}) { TextButton(onClick={vm.action { val url=vm.repo.signedRecitation(r.str("storage_path"));withContextMain { context.startService(android.content.Intent(context,com.msoumaya.androidcoran.audio.RecitationService::class.java).setAction("PLAY_URL").putExtra("url",url)) } }}) { Text("Écouter l’enregistrement") } } };selected?.let { Text("Corrections");corrections.forEach { c -> Panel("Verset ${c.num("verse_id")}",c.str("comment")) } };if(rows.isEmpty()) Text("Aucune récitation chargée") }
}
private suspend fun withContextMain(block: ()->Unit)=kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.Main) { block() }
@Composable fun ReportScreen(vm: CoranViewModel) { var description by rememberSaveable { mutableStateOf("") };var type by rememberSaveable { mutableStateOf("Bug") };PageList { Text("Signaler un dysfonctionnement");listOf("Bug","Affichage","Audio","Notification","Autre").forEach { t->FilterChip(selected=t==type,onClick={type=t},label={Text(t)}) };OutlinedTextField(description,{description=it},label={Text("Description")},minLines=4);Button(onClick={vm.action { require(description.trim().length>=10);vm.repo.insert("app_problem_reports",json("id" to java.util.UUID.randomUUID().toString(),"user_id" to vm.repo.user.value,"type" to type,"description" to description.trim(),"screenshot_path" to null,"app_version" to "0.1.0","platform" to "android","status" to "open"));description="";vm.repo.feedback("Signalement envoyé") }}) { Text("Envoyer le signalement") } } }
